# Generated by Django 3.1.2 on 2020-11-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Maths', 'Mathematics'), ('Bio', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default='Maths', max_length=9)),
                ('bookpdf', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('Maths', 'Mathematics'), ('Bio', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default='Maths', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Maths', 'Mathematics'), ('Bio', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], default='Maths', max_length=9)),
                ('video', models.FileField(upload_to='media/lectures')),
            ],
        ),
    ]
